### ISSUE TITLE
Mockup of UH Site Elements (Navbar/footer/etc)

### ISSUE THREAD

**Issue by ThanhLy1** [HACC2023/Regex#1]
One of us need to work on the main landing page to make it look like the IT Help Desk website.
![potential_ui_look](https://github.com/HACC2023/Regex/assets/123609101/aedadccb-9270-4a20-bb61-b68d8c13f16e)

**Comment by ImamuraDev** [comment]
Specifically, edit the NavBar and Footer components to mimic the one found [here](https://www.hawaii.edu/its/help-desk/index.html). Don't forget the "[Home](#) > AskUs", though that element should probably go into the landing page itself.

Not entirely sure about the exact page body content yet, but most likely will need FAQ similar to image above. Ideally implement modularly so that you can list 8-10, with input for them coming from database/backend.
